# version: '3'
# services:
#   php:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/var/www/html
#     ports:
#       - 8080:80
#     depends_on:
#       - mysql
#   mysql:
#     image: mysql:latest
#     environment:
#       MYSQL_ROOT_PASSWORD:
#       MYSQL_DATABASE: intern_app
#       MYSQL_USER: gautam
#       MYSQL_PASSWORD: gautam
#     volumes:
#       - mysql_data:/var/lib/mysql
# volumes:
#   mysql_data:


version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intern_app
      MYSQL_USER: gautam
      MYSQL_PASSWORD: gautam
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
